### ISSUE TITLE
Configurable Commands Folder(s)

### ISSUE THREAD

**Issue by pascalwacker** [ThomasLeconte/discord-starter-package#10]
Usually when I set up a TS project, I have a `src`  (containing all the .ts files) folder as well as a `dist` folder (containing the transpiled .js files).

While it's possible to simply place all commands in a `./commands` folder at the root level, it would be even more awesome to have a config option to define the command folder/folders.

**Comment by ThomasLeconte** [comment]
Hi ! It was one of my pending ideas, thanks for contribution :) ! I'm going to check your PR soon !

**Comment by ThomasLeconte** [comment]
Commit in develop :  https://github.com/ThomasLeconte/discord-starter-package/commit/d4920c119f38926b8b7269b7bcf9762c4458687c

@pascalwacker I've fixed an uniqueness error, you have made default lib commands registering inside commands folders loop, so commands was declared many times. I made default lib commands registering independent of main code, for better maintenance in future.

**Comment by pascalwacker** [comment]
Good catch, I should have tested it with multiple folders actually >.<

**Comment by ThomasLeconte** [comment]
no problems, Develop branch is made for that 😉 !
