### ISSUE TITLE
Prefix not Working?

### ISSUE THREAD

**Issue by pascalwacker** [ThomasLeconte/discord-starter-package#12]
I'm not sure, if the prefix is not working, or I don't understand it's purpose.

I've set the prefix to: `"/asdf"`  and disabled all commands, except for help, which results in:
```
# - - - - COMMANDS - - - - #
# Slash commands : /asdfhelp
# Basic commands :
# - - - - COMMANDS - - - - #
```
However, in the server, nothing shows up when I enter `/asdfhelp` however `/help` does show up.

Two things I'd expect:

1. The command actually using the prefix
2. The command using camelCase --> `/asdfHelp`

**Comment by ThomasLeconte** [comment]
I'm going to check that, but in my mind Slash Commands can't have custom prefix. Can you try with a basic command ?

For the /help display instead of your expected command, it was a basic reply or a slash command reply ?

**Comment by pascalwacker** [comment]
Ah, I see, with basic commands the prefix works as expected. I'll update the docs and send you a pull request.

**Comment by ThomasLeconte** [comment]
I've just test and effectively, custom prefix only works on basic commands. But custom prefix are also displayed on slash commands items, that's a new issue hehe 😄
![image](https://github.com/ThomasLeconte/discord-starter-package/assets/55429863/9fb97c59-59f3-4110-923c-7c802acc12a6)

**Comment by pascalwacker** [comment]
Yep, that's where my confusion came from (and I've only tested with slash commands :P)

Btw. I've seen usually people prefix their basic commands with `!` like `!roll 1d20` or something like that, so no one triggers the bot by accident, but actually knows there's a "command". Maybe we could add that as a suggestion and `!` as default prefix.

**Comment by ThomasLeconte** [comment]
> Yep, that's where my confusion came from (and I've only tested with slash commands :P)
> 
> Btw. I've seen usually people prefix their basic commands with `!` like `!roll 1d20` or something like that, so no one triggers the bot by accident, but actually knows there's a "command". Maybe we could add that as a suggestion and `!` as default prefix.

I think "/" is better, in most of tutorial I saw this one was used, but I agree with you, "!" is very used too ;)
