### ISSUE TITLE
Discord JS Version Warning

### ISSUE THREAD

**Issue by pascalwacker** [ThomasLeconte/discord-starter-package#14]
On Startup the following warning is shown.
```
🧨 You are using a different version of discord.js ! Please update discord.js package version to 14.9.0 for the best compatibility with discord-starter-package.
```

My `package-lock.json` states:
```
[...]
    "node_modules/discord.js": {
      "version": "14.11.0",
[...]
```

The error should only be shown, if the installed version is `<` the required version

**Comment by ThomasLeconte** [comment]
I had a global try catch arround `semver` methods used for preventing bot initialization fatal error during version check process (i'm working with a symlink, and my package dependency look like `"discord-starter-package": "file:../DiscordBot-Starter",` 😅).

It will be in next release too, thanks for your work @pascalwacker 😄 !
