### ISSUE TITLE
Add an Example Implementation in a Separate Repository

### ISSUE THREAD

**Issue by pascalwacker** [ThomasLeconte/discord-starter-package#9]
Hi, first of all, I wanted to say thanks for your work, as it looks like a pretty good starting point, I'd suggest to add a second repository, something like `ThomasLeconte/discord-starter-example` . The goal would be:

- Implementing this package
- Showing you how to read env variables (as I suspect some people will just hardcode their tokens...)
- How to deploy slash commands to your guild

**Comment by ThomasLeconte** [comment]
Hi again, indeed that should be a good idea, I didn't know how to simplify my README.md, that could be the solution!

**Comment by ThomasLeconte** [comment]
Hi, I made a folder with an example instead of a dedicated repository : [here is the commit](https://github.com/ThomasLeconte/discord-starter-package/commit/70e6719d5bc5baea2647bee9a6eddeb654107598)

**Comment by pascalwacker** [comment]
As an enhancement, maybe we could also add a Typescript version as a second example (in it's own `example-ts` folder)

**Comment by ThomasLeconte** [comment]
> As an enhancement, maybe we could also add a Typescript version as a second example (in it's own `example-ts` folder)

Variables are auto-typed, i don't think a TS example should be useful. Except variables typing, what could be interesting with a TS version ?
